server.port=9092
server.servlet.context-path=/
spring.web.resources.static-locations=classpath:/static/

# gRPC server (Go) connection settings
grpc.server.host=127.0.0.1
grpc.server.port=9100
grpc.server.listen-port=9101

# RocksDB embedded storage; database directory (default is data/rocksdb)
rocksdb.path=data/rocksdb
