server.port=9092
server.servlet.context-path=/
spring.web.resources.static-locations=classpath:/static/

# gRPC server (Go) connection settings
grpc.server.host=127.0.0.1
grpc.server.port=9100
grpc.server.listen-port=9101

# RocksDB embedded storage; database directory (default is data/rocksdb)
rocksdb.path=data/rocksdb

spring.datasource.url=jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=2526
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.type-aliases-package=com.zqyyz.ranksystem
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl